import React,{useEffect,useState} from 'react'
import {Search,SlidersHorizontal,ChevronRight,ArrowLeft,Plug,Layers,Wrench,Puzzle,RotateCcw} from 'lucide-react'
import {host,preview,useValue,bots,instances,notify} from './sdk.jsx'
import {toolFixtures,skillFixtures,pluginFixtures,filterCatalog} from './hermes-catalog.mjs'
import connectors from './connector-fixtures.json'

const tabs=[['skills','Skills',Layers],['toolsets','Tools',Wrench],['connectors','Connectors',Plug],['plugins','Plugins',Puzzle]]
const datasets={skills:skillFixtures,toolsets:toolFixtures,connectors,plugins:pluginFixtures}
function readSaved(){try{return JSON.parse(localStorage.getItem('naclip-preview:capabilities:v1'))||{}}catch{return {}}}
export default function CapabilitiesPage(){
 const s=useValue(preview),param=new URLSearchParams(s.route.split('?')[1]).get('tab'),tab=datasets[param]?param:'skills',title=tabs.find(([id])=>id===tab)[1]
 const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[source,setSource]=useState('all'),[status,setStatus]=useState('all'),[sort,setSort]=useState('name'),[selected,setSelected]=useState(null),[detailOpen,setDetailOpen]=useState(false),[saved,setSaved]=useState(readSaved),[filtersOpen,setFiltersOpen]=useState(false)
 const scope=s.instance+':'+s.profile+':'+tab
 const rows=datasets[tab].map(r=>({...r,enabled:saved[scope]?.[r.id]??r.enabled}))
 const filtered=filterCatalog(rows,{query,category,source,status,sort}),active=filtered.find(r=>r.id===selected)||filtered[0]
 const reset=()=>{setQuery('');setCategory('all');setSource('all');setStatus('all');setSelected(null);setDetailOpen(false)}
 useEffect(reset,[tab,s.instance,s.profile])
 const toggle=row=>{const next={...saved,[scope]:{...saved[scope],[row.id]:!row.enabled}};setSaved(next);try{localStorage.setItem('naclip-preview:capabilities:v1',JSON.stringify(next))}catch{notify('Preview storage is unavailable; the change will last for this visit.')}}
 return <section className="capability-page" aria-label="Capabilities">
  <nav className="capability-tabs" aria-label="Capability tabs">{tabs.map(([id,name,Icon])=><button key={id} aria-current={id===tab?'page':undefined} onClick={()=>host.navigate('/capabilities?tab='+id)}><Icon size={17}/>{name}</button>)}</nav>
  <div className="capability-heading"><div><span className="eyebrow">Capabilities</span><h2>{title}</h2></div><div className="capability-scope"><span>Configuring</span><strong>{bots.find(b=>b.id===s.profile).name}</strong><small>{instances.find(i=>i.id===s.instance).name}</small></div></div>
  <div className="capability-toolbar" data-filters-open={filtersOpen}><label className="catalog-search"><Search size={18}/><input aria-label={'Search '+title.toLowerCase()} placeholder={tab==='toolsets'?'Search tools, names or descriptions…':'Search '+title.toLowerCase()+'…'} value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button aria-label="Clear catalog search" onClick={()=>setQuery('')}>×</button>}</label><button className="catalog-filter-toggle" aria-expanded={filtersOpen} onClick={()=>setFiltersOpen(!filtersOpen)}><SlidersHorizontal size={16}/>Filters</button><div className="catalog-filters"><SlidersHorizontal size={16} aria-hidden="true"/><label>Category<select aria-label="Filter by category" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(rows.map(r=>r.category))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Source<select aria-label="Filter by source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{[...new Set(rows.map(r=>r.source))].sort().map(c=><option key={c}>{c}</option>)}</select></label><label>Status<select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="enabled">{tab==='connectors'?'Added in preview':'Enabled'}</option><option value="disabled">{tab==='connectors'?'Available':'Disabled'}</option></select></label><label>Sort<select aria-label="Sort catalog" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="enabled">Enabled first</option></select></label></div></div>
  <div className="catalog-results"><span>{filtered.length} of {rows.length} sample {title.toLowerCase()}</span><button onClick={reset}><RotateCcw size={14}/>Reset filters</button></div>
  <div className="capability-explorer" data-detail-open={detailOpen}>
   <div className="capability-list" aria-label={title+' results'}>{filtered.map(row=><div key={row.id} className={'capability-row '+(active?.id===row.id?'selected':'')}><button className="capability-select" aria-label={'Inspect '+row.name} aria-current={active?.id===row.id?'true':undefined} onClick={()=>{setSelected(row.id);setDetailOpen(true)}}><span className="catalog-glyph" aria-hidden="true">{row.name.slice(0,1).toUpperCase()}</span><span><strong>{row.name}</strong><small>{row.description}</small><span className="catalog-row-meta">{row.category} · {row.source}</span></span><ChevronRight size={16}/></button>{tab==='connectors'?<button className="catalog-add" onClick={()=>toggle(row)}>{row.enabled?'Remove':'Add'}</button>:<button className="catalog-switch" role="switch" aria-label={'Enable '+row.name+' in preview'} aria-checked={row.enabled} onClick={()=>toggle(row)}><span/></button>}</div>)}{!filtered.length&&<div className="catalog-empty"><Search size={26}/><h3>No matches</h3><p>Try a different search or clear the filters.</p><button className="sdk-button outline" onClick={reset}>Reset filters</button></div>}</div>
   <aside className="capability-detail" aria-label="Capability details"><button className="catalog-back" onClick={()=>setDetailOpen(false)}><ArrowLeft size={16}/>Back to {title.toLowerCase()}</button>{active?<><span className="eyebrow">{active.source} · {active.category}</span><h3>{active.name}</h3><span className={'catalog-status '+(active.enabled?'enabled':'')}>{active.enabled?(tab==='connectors'?'Added in preview':'Enabled in preview'):(tab==='connectors'?'Available':'Disabled in preview')}</span><p>{active.description}</p>{active.tools&&<><h4>Tool names</h4><div className="tool-name-list">{active.tools.map(name=><code key={name}>{name}</code>)}</div></>}{tab==='connectors'&&<dl><dt>Transport</dt><dd>{active.transport.toUpperCase()}</dd><dt>Authentication</dt><dd>{active.auth.replace('_',' ')}</dd></dl>}<h4>Configuration</h4><p className="capability-explanation">{tab==='connectors'?'Native Hermes handles installation, authorization, custom MCP servers and live connection checks.':tab==='plugins'?'Native Hermes retains installation from Git, disk and bundled plugins, enable/disable controls, rescanning and plugin settings.':tab==='skills'?'Native Hermes retains discovery sources, categories, installation, skill details and enable/disable controls.':'Native Hermes retains tool configuration, credentials, enable/disable policies and usage history.'}</p><button className="sdk-button outline" onClick={()=>host.navigate('/settings?tab=keys&kview=tools')}>Tools & Keys</button></>:<p>Select a capability to inspect it.</p>}</aside>
  </div><footer className="capability-footnote">Sample catalog · Changes affect this browser preview only.</footer>
 </section>
}
