import React,{useState} from 'react'
import {Search,ChevronDown,ChevronRight,Sun,Moon} from 'lucide-react'
import {preview,useValue,host,update,currentSelection,instances,selectContext} from './sdk.jsx'
import {settingsSections,settingsRoute,resolveSettings,providers} from './hermes-catalog.mjs'

const providerName=Object.fromEntries(providers.map(p=>[p.id,p.name]))
function ProviderList(){const [query,setQuery]=useState(''),[kind,setKind]=useState('all');const rows=providers.filter(p=>(kind==='all'||p.kind===kind)&&p.name.toLowerCase().includes(query.toLowerCase()));return <><label className="catalog-search"><Search size={18}/><input aria-label="Search providers" placeholder="Search providers…" value={query} onChange={e=>setQuery(e.target.value)}/></label><label className="provider-kind">Provider type<select aria-label="Filter provider type" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All providers</option>{['Cloud','Local','Router','Custom'].map(k=><option key={k}>{k}</option>)}</select></label><div className="provider-directory">{rows.map(p=><div className="provider-entry" key={p.id}><span className="catalog-glyph">{p.name[0]}</span><div><strong>{p.name}</strong><small>{p.kind}</small></div><span className="sample-tag">Sample</span></div>)}</div>{!rows.length&&<p>No providers match this search.</p>}<p className="native-surface-note">The native provider inventory and sign-in/API-key flows stay in Hermes. These entries demonstrate the overlay, with no credentials loaded.</p></>}
export default function SettingsPage({renderAppearance}){
 const s=useValue(preview),{section,page}=resolveSettings(s.route),[query,setQuery]=useState(''),[expanded,setExpanded]=useState({})
 const nav=settingsSections.filter(group=>[group.name,...group.children.map(p=>p.name)].join(' ').toLowerCase().includes(query.toLowerCase()))
 const selection=currentSelection(s),appearance=section.id==='config:appearance'&&(page.id==='theme'||page.id==='general')
 return <div className="settings-shell settings-complete"><nav className="settings-nav" aria-label="Settings categories"><label className="settings-search"><Search size={14}/><input aria-label="Search settings" placeholder="Find a setting…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{nav.map(group=>{const active=group.id===section.id,open=query||(expanded[group.id]??active);return <div className="settings-group" key={group.id}><div className="settings-group-heading"><button aria-current={active?'page':undefined} onClick={()=>host.navigate(settingsRoute(group))}>{group.name}</button><button className="settings-disclosure" aria-label={(open?'Collapse ':'Expand ')+group.name} aria-expanded={!!open} onClick={()=>setExpanded({...expanded,[group.id]:!open})}>{open?<ChevronDown size={14}/>:<ChevronRight size={14}/>}</button></div>{open&&<div className="settings-children">{group.children.filter(p=>!query||group.name.toLowerCase().includes(query.toLowerCase())||p.name.toLowerCase().includes(query.toLowerCase())).map(child=><button key={child.id} aria-current={active&&page.id===child.id?'page':undefined} onClick={()=>host.navigate(settingsRoute(group,child.id))}>{child.name}</button>)}</div>}</div>})}{!nav.length&&<p>No matching settings.</p>}</nav>
 <div className="settings-body"><label className="mobile-setting-picker">Settings page<select aria-label="Choose settings page" value={settingsRoute(section,page.id)} onChange={e=>host.navigate(e.target.value)}>{settingsSections.map(group=><optgroup key={group.id} label={group.name}>{group.children.map(child=><option key={child.id} value={settingsRoute(group,child.id)}>{child.name}</option>)}</optgroup>)}</select></label><span className="eyebrow">Settings · {section.name}</span><h2>{page.name}</h2><p className="settings-summary">{page.summary}</p>
 {appearance?<><div className="setting-row"><div><strong>Appearance mode</strong><small>Use the sun or moon to switch modes.</small></div><button className="icon-button" aria-label={s.dark?'Switch to light mode':'Switch to dark mode'} onClick={()=>update({dark:!s.dark})}>{s.dark?<Sun size={17}/>:<Moon size={17}/>}</button></div>{renderAppearance()}</>:section.id==='providers'?<ProviderList/>:section.id==='config:model'?<><div className="setting-row"><div><strong>{page.id==='main'?'Chat model':page.name}</strong><small>{page.id==='main'?providerName[selection.provider]+' · '+selection.model:'Managed by native Hermes'}</small></div>{page.id==='main'&&<button className="sdk-button outline" onClick={()=>update({panel:'model'})}>Preview chat model</button>}</div><div className="settings-option-list">{(page.id==='main'?['Provider and model','Context length','Reasoning effort','Service tier']:page.id==='fallbacks'?['Fallback order','Provider-specific fallback models']:page.id==='auxiliary'?['Compression model','Vision model','Web extraction model']:['Contributing models','Aggregator model']).map(label=><div key={label}><strong>{label}</strong><span>Native configuration</span></div>)}</div><button className="text-action" onClick={()=>host.navigate('/settings?tab=providers')}>All providers and local runtimes</button></>:section.id==='gateway'?<><div className="gateway-modes">{['Local','SSH','URL + token','Cloud'].map(mode=><span key={mode}>{mode}</span>)}</div>{instances.map(i=><div key={i.id} className="setting-row"><div><strong>{i.name}</strong><small>{i.detail}</small></div><button className="sdk-button outline" onClick={()=>selectContext({instance:i.id})}>{s.instance===i.id?'Selected':'Open instance'}</button></div>)}<button className="text-action" onClick={()=>host.navigate('/settings?tab=providers')}>Model providers, including Anthropic</button></>:section.id==='sessions'&&page.id==='archived'?<button className="sdk-button outline" onClick={()=>{host.navigate('/');update({mode:'sessions',sessionView:'archived',panel:window.innerWidth<1120?'roster':null})}}>Browse archived chats</button>:section.id==='keys'||section.id==='config:advanced'&&page.id==='tools'?<button className="sdk-button outline" onClick={()=>host.navigate('/capabilities?tab=toolsets')}>Browse tools</button>:<div className="settings-option-list">{section.children.map(child=><button key={child.id} onClick={()=>host.navigate(settingsRoute(section,child.id))}><strong>{child.name}</strong><small>{child.summary}</small><ChevronRight size={16}/></button>)}</div>}
 {!appearance&&section.id!=='providers'&&<div className="native-surface-note">This preview maps the native settings page. Hermes retains the actual controls, saved values and policies when the skin is installed.</div>}<div className="settings-footer-links"><button className="text-action" onClick={()=>host.navigate('/capabilities?tab=skills')}>Skills</button><button className="text-action" onClick={()=>host.navigate('/capabilities?tab=toolsets')}>Tools</button><button className="text-action" onClick={()=>host.navigate('/capabilities?tab=connectors')}>Connectors</button><button className="text-action" onClick={()=>host.navigate('/capabilities?tab=plugins')}>Plugins</button></div>
 </div></div>
}
